/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista todos os responsáveis
         * @description Retorna todos os atendentes e a contagem de chamados em aberto (status open ou in_progress)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssigneeOutput"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Cadastra um novo responsável
         * @description Registra um novo membro da equipe de suporte
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Dados do Responsável */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAssigneeInput"];
                };
            };
            responses: {
                /** @description Mensagem de sucesso */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista chamados com paginação, filtros e ordenação
         * @description Retorna uma lista paginada de chamados de acordo com os filtros especificados
         */
        get: {
            parameters: {
                query?: {
                    /** @description Número da página (padrão: 1) */
                    page?: number;
                    /** @description Itens por página (máx: 100, padrão: 10) */
                    page_size?: number;
                    /** @description Campo de ordenação (created_at, priority, status, title) */
                    sort_by?: string;
                    /** @description Sentido da ordenação (asc, desc) */
                    order?: string;
                    /** @description Filtro por status (open, in_progress, resolved, closed) */
                    status?: string;
                    /** @description Filtro por prioridade (low, medium, high) */
                    priority?: string;
                    /** @description Filtro por nome do responsável */
                    assignee?: string;
                    /** @description Busca textual em título e descrição */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedTicketsOutput"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Cria um novo chamado
         * @description Registra um chamado com atribuição manual ou automática (auto_assign: true)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Dados do Chamado */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTicketInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketOutput"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca chamado por ID
         * @description Retorna os detalhes de um chamado específico pelo seu UUID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID do Chamado (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketOutput"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Atualiza responsável ou status de um chamado
         * @description Atualiza apenas o status e/ou o responsável (manual ou automático) de um chamado. O conteúdo do chamado (título e descrição) não pode ser editado.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID do Chamado (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Dados para atualização de status/responsável */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTicketInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketOutput"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Checagem de integridade da API
         * @description Retorna o status de integridade do serviço.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssigneeOutput: {
            created_at?: string;
            id?: string;
            name?: string;
            open_tickets_count?: number;
            updated_at?: string;
        };
        CreateAssigneeInput: {
            name?: string;
        };
        CreateTicketInput: {
            assignee?: string;
            auto_assign?: boolean;
            description?: string;
            priority?: string;
            title?: string;
        };
        ErrorResponse: {
            error?: string;
        };
        PaginatedTicketsOutput: {
            current_page?: number;
            items?: components["schemas"]["TicketOutput"][];
            page_size?: number;
            total_items?: number;
            total_pages?: number;
        };
        TicketOutput: {
            assignee?: string;
            assignee_details?: components["schemas"]["AssigneeOutput"];
            assignee_id?: string;
            created_at?: string;
            description?: string;
            id?: string;
            priority?: string;
            status?: string;
            title?: string;
            updated_at?: string;
        };
        UpdateTicketInput: {
            assignee?: string;
            auto_assign?: boolean;
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
