// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountOpenTicketsByAssignee(ctx context.Context) ([]CountOpenTicketsByAssigneeRow, error)
	CountTicketsWithFilter(ctx context.Context, arg CountTicketsWithFilterParams) (int64, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) error
	FindAssigneeByName(ctx context.Context, name string) (Assignee, error)
	FindLeastLoadedAssignee(ctx context.Context) (Assignee, error)
	FindTicketByID(ctx context.Context, id pgtype.UUID) (FindTicketByIDRow, error)
	ListAssignees(ctx context.Context) ([]Assignee, error)
	ListTicketsWithFilterAndSort(ctx context.Context, arg ListTicketsWithFilterAndSortParams) ([]ListTicketsWithFilterAndSortRow, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (int64, error)
	UpsertAssignee(ctx context.Context, arg UpsertAssigneeParams) error
}

var _ Querier = (*Queries)(nil)
