// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_ticket.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenTicketsByAssignee = `-- name: CountOpenTicketsByAssignee :many
SELECT a.name AS assignee_name, COUNT(t.id)::int AS open_count
FROM tickets t
JOIN assignees a ON a.id = t.assignee_id
WHERE t.status IN ('open', 'in_progress')
GROUP BY a.name
`

type CountOpenTicketsByAssigneeRow struct {
	AssigneeName string `json:"assignee_name"`
	OpenCount    int32  `json:"open_count"`
}

func (q *Queries) CountOpenTicketsByAssignee(ctx context.Context) ([]CountOpenTicketsByAssigneeRow, error) {
	rows, err := q.db.Query(ctx, countOpenTicketsByAssignee)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOpenTicketsByAssigneeRow
	for rows.Next() {
		var i CountOpenTicketsByAssigneeRow
		if err := rows.Scan(&i.AssigneeName, &i.OpenCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTicketsWithFilter = `-- name: CountTicketsWithFilter :one
SELECT COUNT(*)
FROM tickets t
JOIN assignees a ON a.id = t.assignee_id
WHERE ($1::text IS NULL OR t.status = $1)
  AND ($2::text IS NULL OR t.priority = $2)
  AND ($3::text IS NULL OR LOWER(a.name) = LOWER($3))
  AND ($4::text IS NULL OR LOWER(t.title) LIKE ('%' || LOWER($4::text) || '%') OR LOWER(t.description) LIKE ('%' || LOWER($4::text) || '%'))
`

type CountTicketsWithFilterParams struct {
	Status   pgtype.Text `json:"status"`
	Priority pgtype.Text `json:"priority"`
	Assignee pgtype.Text `json:"assignee"`
	Search   pgtype.Text `json:"search"`
}

func (q *Queries) CountTicketsWithFilter(ctx context.Context, arg CountTicketsWithFilterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsWithFilter,
		arg.Status,
		arg.Priority,
		arg.Assignee,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :exec
INSERT INTO tickets (id, title, description, priority, status, assignee_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateTicketParams struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Priority    string             `json:"priority"`
	Status      string             `json:"status"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) error {
	_, err := q.db.Exec(ctx, createTicket,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.AssigneeID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findTicketByID = `-- name: FindTicketByID :one
SELECT 
    t.id, t.title, t.description, t.priority, t.status, t.assignee_id, t.created_at, t.updated_at,
    a.id AS assignee_ref_id, a.name AS assignee_name, a.created_at AS assignee_created_at, a.updated_at AS assignee_updated_at
FROM tickets t
JOIN assignees a ON a.id = t.assignee_id
WHERE t.id = $1
LIMIT 1
`

type FindTicketByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Priority          string             `json:"priority"`
	Status            string             `json:"status"`
	AssigneeID        pgtype.UUID        `json:"assignee_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AssigneeRefID     pgtype.UUID        `json:"assignee_ref_id"`
	AssigneeName      string             `json:"assignee_name"`
	AssigneeCreatedAt pgtype.Timestamptz `json:"assignee_created_at"`
	AssigneeUpdatedAt pgtype.Timestamptz `json:"assignee_updated_at"`
}

func (q *Queries) FindTicketByID(ctx context.Context, id pgtype.UUID) (FindTicketByIDRow, error) {
	row := q.db.QueryRow(ctx, findTicketByID, id)
	var i FindTicketByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssigneeRefID,
		&i.AssigneeName,
		&i.AssigneeCreatedAt,
		&i.AssigneeUpdatedAt,
	)
	return i, err
}

const listTicketsWithFilterAndSort = `-- name: ListTicketsWithFilterAndSort :many
SELECT 
    t.id, t.title, t.description, t.priority, t.status, t.assignee_id, t.created_at, t.updated_at,
    a.id AS assignee_ref_id, a.name AS assignee_name, a.created_at AS assignee_created_at, a.updated_at AS assignee_updated_at
FROM tickets t
JOIN assignees a ON a.id = t.assignee_id
WHERE ($1::text IS NULL OR t.status = $1)
  AND ($2::text IS NULL OR t.priority = $2)
  AND ($3::text IS NULL OR LOWER(a.name) = LOWER($3))
  AND ($4::text IS NULL OR LOWER(t.title) LIKE ('%' || LOWER($4::text) || '%') OR LOWER(t.description) LIKE ('%' || LOWER($4::text) || '%'))
ORDER BY
  -- Priority ASC
  CASE WHEN $5::text = 'priority' AND $6::text = 'asc' THEN (CASE t.priority WHEN 'low' THEN 1 WHEN 'medium' THEN 2 WHEN 'high' THEN 3 ELSE 0 END) END ASC,
  -- Priority DESC
  CASE WHEN $5::text = 'priority' AND $6::text = 'desc' THEN (CASE t.priority WHEN 'low' THEN 1 WHEN 'medium' THEN 2 WHEN 'high' THEN 3 ELSE 0 END) END DESC,

  -- Status ASC
  CASE WHEN $5::text = 'status' AND $6::text = 'asc' THEN t.status END ASC,
  -- Status DESC
  CASE WHEN $5::text = 'status' AND $6::text = 'desc' THEN t.status END DESC,

  -- Title ASC
  CASE WHEN $5::text = 'title' AND $6::text = 'asc' THEN t.title END ASC,
  -- Title DESC
  CASE WHEN $5::text = 'title' AND $6::text = 'desc' THEN t.title END DESC,

  -- CreatedAt ASC
  CASE WHEN $5::text = 'created_at' AND $6::text = 'asc' THEN t.created_at END ASC,
  -- CreatedAt DESC (default fallback)
  CASE WHEN ($5::text = 'created_at' AND $6::text = 'desc') OR ($5::text NOT IN ('priority', 'status', 'title', 'created_at')) THEN t.created_at END DESC,

  t.id DESC
OFFSET $7::int
LIMIT $8::int
`

type ListTicketsWithFilterAndSortParams struct {
	Status     pgtype.Text `json:"status"`
	Priority   pgtype.Text `json:"priority"`
	Assignee   pgtype.Text `json:"assignee"`
	Search     pgtype.Text `json:"search"`
	SortBy     string      `json:"sort_by"`
	SortOrder  string      `json:"sort_order"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListTicketsWithFilterAndSortRow struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Priority          string             `json:"priority"`
	Status            string             `json:"status"`
	AssigneeID        pgtype.UUID        `json:"assignee_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AssigneeRefID     pgtype.UUID        `json:"assignee_ref_id"`
	AssigneeName      string             `json:"assignee_name"`
	AssigneeCreatedAt pgtype.Timestamptz `json:"assignee_created_at"`
	AssigneeUpdatedAt pgtype.Timestamptz `json:"assignee_updated_at"`
}

func (q *Queries) ListTicketsWithFilterAndSort(ctx context.Context, arg ListTicketsWithFilterAndSortParams) ([]ListTicketsWithFilterAndSortRow, error) {
	rows, err := q.db.Query(ctx, listTicketsWithFilterAndSort,
		arg.Status,
		arg.Priority,
		arg.Assignee,
		arg.Search,
		arg.SortBy,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsWithFilterAndSortRow
	for rows.Next() {
		var i ListTicketsWithFilterAndSortRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssigneeRefID,
			&i.AssigneeName,
			&i.AssigneeCreatedAt,
			&i.AssigneeUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :execrows
UPDATE tickets
SET title = $2,
    description = $3,
    priority = $4,
    status = $5,
    assignee_id = $6,
    updated_at = $7
WHERE id = $1
`

type UpdateTicketParams struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Priority    string             `json:"priority"`
	Status      string             `json:"status"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTicket,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.AssigneeID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
