// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_assignee.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAssigneeByName = `-- name: FindAssigneeByName :one
SELECT id, name, created_at, updated_at
FROM assignees
WHERE LOWER(name) = LOWER($1::text)
LIMIT 1
`

func (q *Queries) FindAssigneeByName(ctx context.Context, name string) (Assignee, error) {
	row := q.db.QueryRow(ctx, findAssigneeByName, name)
	var i Assignee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findLeastLoadedAssignee = `-- name: FindLeastLoadedAssignee :one
SELECT a.id, a.name, a.created_at, a.updated_at
FROM assignees a
LEFT JOIN tickets t ON t.assignee_id = a.id AND t.status IN ('open', 'in_progress')
GROUP BY a.id, a.name, a.created_at, a.updated_at
ORDER BY COUNT(t.id) ASC, a.name ASC
LIMIT 1
`

func (q *Queries) FindLeastLoadedAssignee(ctx context.Context) (Assignee, error) {
	row := q.db.QueryRow(ctx, findLeastLoadedAssignee)
	var i Assignee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignees = `-- name: ListAssignees :many
SELECT id, name, created_at, updated_at
FROM assignees
ORDER BY name ASC
`

func (q *Queries) ListAssignees(ctx context.Context) ([]Assignee, error) {
	rows, err := q.db.Query(ctx, listAssignees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignee
	for rows.Next() {
		var i Assignee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssignee = `-- name: UpsertAssignee :exec
INSERT INTO assignees (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    updated_at = EXCLUDED.updated_at
`

type UpsertAssigneeParams struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAssignee(ctx context.Context, arg UpsertAssigneeParams) error {
	_, err := q.db.Exec(ctx, upsertAssignee,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
